# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :server => {
    :box => "opensuse/Leap-15.3.x86_64",
  },
  :client => {
    :box => "opensuse/Leap-15.3.x86_64",
  }
}

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
  end

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box]

    end
  end

  config.vm.define :server do |box|
    box.vm.network "private_network", ip: "192.168.56.10"

    box.vm.provision "install_nfs", type: "shell", inline: "zypper in -y nfs-kernel-server"
    box.vm.provision "configure_nfs", type: "shell" do |s|
      s.inline = <<'END'
mkdir -pv /srv/nfs/upload
chmod 777 /srv/nfs/upload                               # allow everyone
echo '/srv/nfs *(rw) ' >> /etc/exports                  # export share
systemctl enable --now nfsserver                        # start NFS server
END
    end

  end

  config.vm.define :client do |box|
    box.vm.network "private_network", ip: "192.168.56.20"

    box.vm.provision "install_nfs_client", type: "shell", inline: "zypper in -y nfs-client"
  end

  config.vm.provision "opensuse_enable_docs", type: "shell",
                      inline: "
grep -i opensuse /etc/os-release >/dev/null 2>&1 || exit 1
config=/etc/zypp/zypp.conf
{ grep '^rpm.install.excludedocs' $config >/dev/null 2>&1 &&
    sed -i 's/^rpm.install.excludedocs.*/rpm.install.excludedocs = no/' $config ; } ||
echo 'rpm.install.excludedocs = yes' >> $config

zypper in -y man
"
end
